export const SUPPORTED_LANGUAGES = ["ms", "en"] as const;

export type Language = (typeof SUPPORTED_LANGUAGES)[number];

export const RESOURCE_CATALOG_VERSION = "1.2.0" as const;

export const MESSAGE_KEYS_BY_SECTION = {
  navigation: [
    "navigation.appName",
    "navigation.skipToContent",
    "navigation.languageLabel",
    "navigation.languageMalay",
    "navigation.languageEnglish",
    "navigation.guidance",
    "navigation.checklist",
    "navigation.directory",
    "navigation.chat",
    "navigation.privacy",
    "navigation.limitations",
    "navigation.emergencyAction",
  ],
  guidance: [
    "guidance.heading",
    "guidance.description",
    "guidance.source",
    "guidance.updatedAt",
    "guidance.reviewedStatus",
    "guidance.demoStatus",
    "guidance.nonEndorsement",
    "guidance.contentUnavailable",
  ],
  checklist: [
    "checklist.heading",
    "checklist.description",
    "checklist.householdSize",
    "checklist.hasChildren",
    "checklist.hasElderlyMembers",
    "checklist.needsMobilityAssistance",
    "checklist.hasPets",
    "checklist.hasTransport",
    "checklist.generate",
    "checklist.complete",
    "checklist.incomplete",
    "checklist.changesAnnouncement",
    "checklist.versionChanged",
    "checklist.privacyHint",
    "checklist.print",
    "checklist.items.drinkingWater",
    "checklist.items.shelfStableFood",
    "checklist.items.importantDocuments",
    "checklist.items.lightingRadio",
    "checklist.items.emergencyPlan",
    "checklist.items.extraSupplies",
    "checklist.items.childrenSupplies",
    "checklist.items.elderlySupplies",
    "checklist.items.mobilityPlan",
    "checklist.items.householdSupportPlan",
    "checklist.items.petSupplies",
    "checklist.items.vehicleReadiness",
    "checklist.items.alternateTransport",
    "checklist.explanations.largeHousehold",
    "checklist.explanations.children",
    "checklist.explanations.elderlyMembers",
    "checklist.explanations.mobilityAssistance",
    "checklist.explanations.pets",
    "checklist.explanations.transportAvailable",
    "checklist.explanations.transportUnavailable",
  ],
  directory: [
    "directory.heading",
    "directory.description",
    "directory.searchLabel",
    "directory.searchPlaceholder",
    "directory.role",
    "directory.state",
    "directory.district",
    "directory.phone",
    "directory.source",
    "directory.lastUpdated",
    "directory.contactUnavailable",
    "directory.callAction",
    "directory.externalLinkNotice",
  ],
  chat: [
    "chat.heading",
    "chat.description",
    "chat.inputLabel",
    "chat.send",
    "chat.answerMode",
    "chat.citation",
    "chat.citations",
    "chat.sourceDetails",
    "chat.insufficientEvidence",
    "chat.emergencyHeading",
    "chat.callEmergency",
    "chat.avoidFloodwater",
    "chat.followResponders",
    "chat.cannotDispatch",
    "chat.cannotMonitor",
    "chat.cannotGuaranteeSafety",
    "chat.ambiguousEmergency",
  ],
  errors: [
    "errors.missingContent",
    "errors.validation",
    "errors.invalidRequest",
    "errors.serverUnavailable",
    "errors.storageUnavailable",
    "errors.sourceUnavailable",
    "errors.providerTimeout",
    "errors.providerInvalid",
    "errors.unexpected",
    "errors.retry",
    "errors.safeReturn",
  ],
  privacy: [
    "privacy.heading",
    "privacy.noAccount",
    "privacy.sharedDeviceNotice",
    "privacy.storageAllowlist",
    "privacy.retention",
    "privacy.clearProcedure",
    "privacy.clearAction",
    "privacy.clearConfirm",
    "privacy.memoryFallback",
    "privacy.chatNotStored",
    "privacy.noAnalytics",
    "privacy.enabledIntegrations",
    "privacy.noneEnabled",
  ],
  limitations: [
    "limitations.heading",
    "limitations.informationOnly",
    "limitations.noRescueDispatch",
    "limitations.noReports",
    "limitations.noPayments",
    "limitations.noAccounts",
    "limitations.noRoutes",
    "limitations.noForecasts",
    "limitations.noSafetyGuarantee",
    "limitations.noProfessionalAdvice",
    "limitations.noEndorsement",
    "limitations.unavailable",
  ],
  freshness: [
    "freshness.current",
    "freshness.stale",
    "freshness.unavailable",
    "freshness.sourceTimestamp",
    "freshness.retrievalTimestamp",
    "freshness.lastUpdated",
    "freshness.staleWarning",
    "freshness.replacementReason",
  ],
  demoLabels: [
    "demoLabels.demoMode",
    "demoLabels.demoData",
    "demoLabels.demoGuidance",
    "demoLabels.notCurrentOperational",
    "demoLabels.liveData",
    "demoLabels.reviewedGuidance",
    "demoLabels.providerMode",
    "demoLabels.providerAvailability",
    "demoLabels.providerAvailable",
    "demoLabels.providerUnavailable",
    "demoLabels.providerVerification",
    "demoLabels.providerVerified",
    "demoLabels.providerUnverified",
    "demoLabels.providerFreshness",
    "demoLabels.fallbackProvider",
    "demoLabels.fallbackActive",
    "demoLabels.providerErrorCode",
    "demoLabels.providerStatus",
    "demoLabels.providerStatusLoading",
    "demoLabels.providerStatusUpdated",
    "demoLabels.providerStatusUnavailable",
  ],
} as const;

export type MessageSection = keyof typeof MESSAGE_KEYS_BY_SECTION;
type SectionMessageKeys = (typeof MESSAGE_KEYS_BY_SECTION)[MessageSection];
export type MessageKey = SectionMessageKeys[number];

export const MESSAGE_KEYS = Object.freeze(
  Object.values(MESSAGE_KEYS_BY_SECTION).flat(),
) as readonly MessageKey[];

export const SAFETY_MESSAGES_BY_CATEGORY = {
  emergency_escalation: [
    "navigation.emergencyAction",
    "chat.emergencyHeading",
    "chat.callEmergency",
    "chat.ambiguousEmergency",
  ],
  water_safety: ["chat.avoidFloodwater", "chat.followResponders"],
  rescue_limitations: [
    "chat.cannotDispatch",
    "chat.cannotMonitor",
    "chat.cannotGuaranteeSafety",
    "limitations.noRescueDispatch",
    "limitations.noSafetyGuarantee",
  ],
  evidence_limitations: [
    "chat.insufficientEvidence",
    "guidance.contentUnavailable",
    "directory.contactUnavailable",
    "errors.sourceUnavailable",
  ],
  scope_limitations: [
    "limitations.informationOnly",
    "limitations.noReports",
    "limitations.noPayments",
    "limitations.noAccounts",
    "limitations.noRoutes",
    "limitations.noForecasts",
    "limitations.noProfessionalAdvice",
    "limitations.unavailable",
  ],
  privacy: [
    "checklist.privacyHint",
    "privacy.sharedDeviceNotice",
    "privacy.storageAllowlist",
    "privacy.chatNotStored",
    "privacy.noAnalytics",
  ],
  freshness: [
    "freshness.stale",
    "freshness.unavailable",
    "freshness.staleWarning",
    "freshness.replacementReason",
  ],
  demo_status: [
    "demoLabels.demoMode",
    "demoLabels.demoData",
    "demoLabels.demoGuidance",
    "demoLabels.notCurrentOperational",
  ],
  availability_errors: [
    "errors.missingContent",
    "errors.validation",
    "errors.serverUnavailable",
    "errors.storageUnavailable",
    "errors.providerTimeout",
    "errors.providerInvalid",
    "errors.unexpected",
  ],
  non_endorsement: [
    "guidance.nonEndorsement",
    "limitations.noEndorsement",
  ],
} as const satisfies Readonly<
  Record<string, readonly MessageKey[]>
>;

export type SafetyMessageCategory = keyof typeof SAFETY_MESSAGES_BY_CATEGORY;

export interface ResourceCatalog {
  readonly version: typeof RESOURCE_CATALOG_VERSION;
  readonly language: Language;
  readonly messages: Readonly<Record<MessageKey, string>>;
  readonly safetyMessages: Readonly<
    Record<SafetyMessageCategory, readonly MessageKey[]>
  >;
}

const englishMessages = {
  "navigation.appName": "Banjir Ready",
  "navigation.skipToContent": "Skip to main content",
  "navigation.languageLabel": "Language",
  "navigation.languageMalay": "Bahasa Melayu",
  "navigation.languageEnglish": "English",
  "navigation.guidance": "Guidance",
  "navigation.checklist": "Checklist",
  "navigation.directory": "Agency directory",
  "navigation.chat": "Preparedness chat",
  "navigation.privacy": "Privacy",
  "navigation.limitations": "Limitations",
  "navigation.emergencyAction": "Emergency help",
  "guidance.heading": "Flood preparedness guidance",
  "guidance.description": "Read practical steps for preparing for floods.",
  "guidance.source": "Source",
  "guidance.updatedAt": "Updated",
  "guidance.reviewedStatus": "Reviewed guidance",
  "guidance.demoStatus": "Demo guidance",
  "guidance.nonEndorsement": "Guidance status does not represent government endorsement.",
  "guidance.contentUnavailable": "Guidance is unavailable. Use a listed official source for further information.",
  "checklist.heading": "Preparedness checklist",
  "checklist.description": "Create a checklist using optional household details.",
  "checklist.householdSize": "Household size",
  "checklist.hasChildren": "Children in the household",
  "checklist.hasElderlyMembers": "Elderly members in the household",
  "checklist.needsMobilityAssistance": "Mobility assistance needed",
  "checklist.hasPets": "Pets in the household",
  "checklist.hasTransport": "Transport available",
  "checklist.generate": "Generate checklist",
  "checklist.complete": "Completed",
  "checklist.incomplete": "Not completed",
  "checklist.changesAnnouncement": "Checklist updated: {added} added, {retained} retained, {removed} removed.",
  "checklist.versionChanged": "The checklist rules changed. Your checklist was regenerated using the current version.",
  "checklist.privacyHint": "Household checklist details stay on this device and are not sent to the server.",
  "checklist.print": "Print preparedness plan",
  "checklist.items.drinkingWater": "Store drinking water.",
  "checklist.items.shelfStableFood": "Prepare shelf-stable food.",
  "checklist.items.importantDocuments": "Protect copies of important documents.",
  "checklist.items.lightingRadio": "Prepare lighting, spare batteries, and a battery-powered radio.",
  "checklist.items.emergencyPlan": "Keep emergency contacts and discuss a household meeting plan.",
  "checklist.items.extraSupplies": "Increase essential supplies for the selected household size.",
  "checklist.items.childrenSupplies": "Prepare age-appropriate supplies for children.",
  "checklist.items.elderlySupplies": "Prepare essential daily aids and supplies for elderly household members.",
  "checklist.items.mobilityPlan": "Plan accessible assistance and evacuation support.",
  "checklist.items.householdSupportPlan": "Assign support and supervision responsibilities.",
  "checklist.items.petSupplies": "Prepare pet food, carriers, identification, and sanitation supplies.",
  "checklist.items.vehicleReadiness": "Keep available transport fuelled and ready for official instructions.",
  "checklist.items.alternateTransport": "Identify official assistance contacts and a backup transport arrangement.",
  "checklist.explanations.largeHousehold": "Included because a household size of five or more was selected.",
  "checklist.explanations.children": "Included because children in the household were selected.",
  "checklist.explanations.elderlyMembers": "Included because elderly household members were selected.",
  "checklist.explanations.mobilityAssistance": "Included because mobility assistance was selected.",
  "checklist.explanations.pets": "Included because pets in the household were selected.",
  "checklist.explanations.transportAvailable": "Included because available transport was selected.",
  "checklist.explanations.transportUnavailable": "Included because transport was selected as unavailable.",
  "directory.heading": "Malaysian agency directory",
  "directory.description": "Find documented agency roles and contact channels.",
  "directory.searchLabel": "Search agencies",
  "directory.searchPlaceholder": "Search by agency, role, state, or district",
  "directory.role": "Agency role",
  "directory.state": "State",
  "directory.district": "District",
  "directory.phone": "Telephone",
  "directory.source": "Source",
  "directory.lastUpdated": "Last updated",
  "directory.contactUnavailable": "Contact information is unavailable. Refer to the listed source.",
  "directory.callAction": "Call agency",
  "directory.externalLinkNotice": "External link opens an official information portal; it is not an application integration.",
  "chat.heading": "Flood preparedness chat",
  "chat.description": "Ask about flood preparedness using the approved local knowledge corpus.",
  "chat.inputLabel": "Preparedness question",
  "chat.send": "Send question",
  "chat.answerMode": "Answer mode",
  "chat.citation": "Citation",
  "chat.citations": "Citations",
  "chat.sourceDetails": "Source details",
  "chat.insufficientEvidence": "There is not enough approved evidence to answer that request safely.",
  "chat.emergencyHeading": "Get emergency help now",
  "chat.callEmergency": "Call 999",
  "chat.avoidFloodwater": "Do not walk, swim, or drive through moving or unknown-depth floodwater.",
  "chat.followResponders": "Follow instructions from emergency personnel.",
  "chat.cannotDispatch": "BanjirReady cannot dispatch rescue services.",
  "chat.cannotMonitor": "BanjirReady cannot monitor rescue requests.",
  "chat.cannotGuaranteeSafety": "BanjirReady cannot guarantee current safety.",
  "chat.ambiguousEmergency": "Your message may describe an emergency. Contact emergency services first, then clarify only if it is safe to do so.",
  "errors.missingContent": "This content is unavailable in English.",
  "errors.validation": "Check the highlighted information and try again.",
  "errors.invalidRequest": "The request was not accepted.",
  "errors.serverUnavailable": "The local service is unavailable. Previously loaded emergency guidance remains available.",
  "errors.storageUnavailable": "Saving is unavailable. You can continue using this session in memory.",
  "errors.sourceUnavailable": "The source is unavailable. No value has been guessed or substituted.",
  "errors.providerTimeout": "The optional provider did not respond in time. Safe local fallback content is being used.",
  "errors.providerInvalid": "The optional provider returned invalid data. Safe local fallback content is being used.",
  "errors.unexpected": "Something went wrong. No personal information was saved for debugging.",
  "errors.retry": "Retry once",
  "errors.safeReturn": "Return to safety guidance",
  "privacy.heading": "Privacy and local data",
  "privacy.noAccount": "No account or identity is required for baseline features.",
  "privacy.sharedDeviceNotice": "This browser profile may be shared. Checklist preferences saved here may be visible to other users of this profile.",
  "privacy.storageAllowlist": "Local storage contains only language preference, six checklist fields, checklist rule version, stable item completion states, and acknowledged notices.",
  "privacy.retention": "Allowed data remains in this browser profile until it is cleared or browser storage is removed.",
  "privacy.clearProcedure": "After confirmation, clearing data removes every BanjirReady-prefixed key and leaves unrelated browser data unchanged.",
  "privacy.clearAction": "Clear BanjirReady data",
  "privacy.clearConfirm": "Confirm clearing locally stored BanjirReady data.",
  "privacy.memoryFallback": "If browser storage is unavailable, features continue in memory for this session.",
  "privacy.chatNotStored": "Chat message text is not stored after response or abort processing ends.",
  "privacy.noAnalytics": "Analytics, advertising, session replay, geolocation, and background location collection are not enabled.",
  "privacy.enabledIntegrations": "Enabled external integrations",
  "privacy.noneEnabled": "No external integrations are enabled.",
  "limitations.heading": "Limitations",
  "limitations.informationOnly": "BanjirReady provides preparedness information only.",
  "limitations.noRescueDispatch": "Rescue requests, dispatch, and rescue monitoring are unavailable.",
  "limitations.noReports": "User reports and crowdsourcing are unavailable.",
  "limitations.noPayments": "Payments, donations, and subscriptions are unavailable.",
  "limitations.noAccounts": "Accounts, sign-in, and cross-device synchronization are unavailable.",
  "limitations.noRoutes": "Evacuation route calculation and safe-route guarantees are unavailable.",
  "limitations.noForecasts": "Flood forecasting and water-level prediction are unavailable.",
  "limitations.noSafetyGuarantee": "BanjirReady cannot state that a place is currently safe or guarantee current safety.",
  "limitations.noProfessionalAdvice": "BanjirReady does not provide clinical, legal, engineering, or emergency-professional advice.",
  "limitations.noEndorsement": "Content and review status do not represent government endorsement.",
  "limitations.unavailable": "This capability is outside the BanjirReady MVP and is unavailable.",
  "freshness.current": "Current under the configured freshness policy",
  "freshness.stale": "Stale",
  "freshness.unavailable": "Source unavailable",
  "freshness.sourceTimestamp": "Source timestamp",
  "freshness.retrievalTimestamp": "Retrieval timestamp",
  "freshness.lastUpdated": "Last updated",
  "freshness.staleWarning": "This information is stale. Check the source timestamp before acting.",
  "freshness.replacementReason": "Stale source data was replaced with deterministic demo data.",
  "demoLabels.demoMode": "Demo Mode / Mod Demo",
  "demoLabels.demoData": "Demo Data / Data Demo",
  "demoLabels.demoGuidance": "Demo Guidance / Panduan Demo",
  "demoLabels.notCurrentOperational": "Not current operational information / Bukan maklumat operasi semasa",
  "demoLabels.liveData": "Live data",
  "demoLabels.reviewedGuidance": "Reviewed guidance",
  "demoLabels.providerMode": "Provider mode",
  "demoLabels.providerAvailability": "Availability",
  "demoLabels.providerAvailable": "Provider available",
  "demoLabels.providerUnavailable": "Provider unavailable",
  "demoLabels.providerVerification": "Verification",
  "demoLabels.providerVerified": "Verified",
  "demoLabels.providerUnverified": "Unverified",
  "demoLabels.providerFreshness": "Freshness",
  "demoLabels.fallbackProvider": "Fallback provider",
  "demoLabels.fallbackActive": "Credential-free fallback active",
  "demoLabels.providerErrorCode": "Safe error code",
  "demoLabels.providerStatus": "Provider status and fallbacks",
  "demoLabels.providerStatusLoading": "Refreshing provider status. Previously loaded status remains available.",
  "demoLabels.providerStatusUpdated": "Provider status updated.",
  "demoLabels.providerStatusUnavailable": "Provider status service unavailable",
} as const satisfies Readonly<Record<MessageKey, string>>;

const malayMessages = {
  "navigation.appName": "Banjir Ready",
  "navigation.skipToContent": "Langkau ke kandungan utama",
  "navigation.languageLabel": "Bahasa",
  "navigation.languageMalay": "Bahasa Melayu",
  "navigation.languageEnglish": "English",
  "navigation.guidance": "Panduan",
  "navigation.checklist": "Senarai semak",
  "navigation.directory": "Direktori agensi",
  "navigation.chat": "Sembang kesiapsiagaan",
  "navigation.privacy": "Privasi",
  "navigation.limitations": "Batasan",
  "navigation.emergencyAction": "Bantuan kecemasan",
  "guidance.heading": "Panduan kesiapsiagaan banjir",
  "guidance.description": "Baca langkah praktikal untuk bersiap sedia menghadapi banjir.",
  "guidance.source": "Sumber",
  "guidance.updatedAt": "Dikemas kini",
  "guidance.reviewedStatus": "Panduan disemak",
  "guidance.demoStatus": "Panduan demo",
  "guidance.nonEndorsement": "Status panduan tidak mewakili pengendorsan kerajaan.",
  "guidance.contentUnavailable": "Panduan tidak tersedia. Gunakan sumber rasmi yang disenaraikan untuk maklumat lanjut.",
  "checklist.heading": "Senarai semak kesiapsiagaan",
  "checklist.description": "Cipta senarai semak menggunakan butiran isi rumah pilihan.",
  "checklist.householdSize": "Saiz isi rumah",
  "checklist.hasChildren": "Kanak-kanak dalam isi rumah",
  "checklist.hasElderlyMembers": "Warga emas dalam isi rumah",
  "checklist.needsMobilityAssistance": "Bantuan pergerakan diperlukan",
  "checklist.hasPets": "Haiwan peliharaan dalam isi rumah",
  "checklist.hasTransport": "Pengangkutan tersedia",
  "checklist.generate": "Jana senarai semak",
  "checklist.complete": "Selesai",
  "checklist.incomplete": "Belum selesai",
  "checklist.changesAnnouncement": "Senarai semak dikemas kini: {added} ditambah, {retained} dikekalkan, {removed} dibuang.",
  "checklist.versionChanged": "Peraturan senarai semak telah berubah. Senarai semak anda dijana semula menggunakan versi semasa.",
  "checklist.privacyHint": "Butiran senarai semak isi rumah kekal pada peranti ini dan tidak dihantar ke pelayan.",
  "checklist.print": "Cetak pelan kesiapsiagaan",
  "checklist.items.drinkingWater": "Simpan air minuman.",
  "checklist.items.shelfStableFood": "Sediakan makanan tahan lama.",
  "checklist.items.importantDocuments": "Lindungi salinan dokumen penting.",
  "checklist.items.lightingRadio": "Sediakan lampu, bateri ganti dan radio berkuasa bateri.",
  "checklist.items.emergencyPlan": "Simpan hubungan kecemasan dan bincangkan pelan pertemuan isi rumah.",
  "checklist.items.extraSupplies": "Tambah bekalan penting mengikut saiz isi rumah yang dipilih.",
  "checklist.items.childrenSupplies": "Sediakan bekalan yang bersesuaian dengan umur kanak-kanak.",
  "checklist.items.elderlySupplies": "Sediakan alat bantuan dan bekalan harian penting untuk warga emas dalam isi rumah.",
  "checklist.items.mobilityPlan": "Rancang bantuan yang boleh diakses dan sokongan pemindahan.",
  "checklist.items.householdSupportPlan": "Tetapkan tanggungjawab sokongan dan pengawasan.",
  "checklist.items.petSupplies": "Sediakan makanan, bekas pembawa, pengenalan dan bekalan kebersihan haiwan peliharaan.",
  "checklist.items.vehicleReadiness": "Pastikan pengangkutan yang tersedia mempunyai bahan api dan bersedia mengikut arahan rasmi.",
  "checklist.items.alternateTransport": "Kenal pasti hubungan bantuan rasmi dan aturan pengangkutan sandaran.",
  "checklist.explanations.largeHousehold": "Disertakan kerana saiz isi rumah lima orang atau lebih dipilih.",
  "checklist.explanations.children": "Disertakan kerana kanak-kanak dalam isi rumah dipilih.",
  "checklist.explanations.elderlyMembers": "Disertakan kerana warga emas dalam isi rumah dipilih.",
  "checklist.explanations.mobilityAssistance": "Disertakan kerana bantuan pergerakan dipilih.",
  "checklist.explanations.pets": "Disertakan kerana haiwan peliharaan dalam isi rumah dipilih.",
  "checklist.explanations.transportAvailable": "Disertakan kerana pengangkutan tersedia dipilih.",
  "checklist.explanations.transportUnavailable": "Disertakan kerana pengangkutan dipilih sebagai tidak tersedia.",
  "directory.heading": "Direktori agensi Malaysia",
  "directory.description": "Cari peranan agensi dan saluran hubungan yang didokumenkan.",
  "directory.searchLabel": "Cari agensi",
  "directory.searchPlaceholder": "Cari mengikut agensi, peranan, negeri atau daerah",
  "directory.role": "Peranan agensi",
  "directory.state": "Negeri",
  "directory.district": "Daerah",
  "directory.phone": "Telefon",
  "directory.source": "Sumber",
  "directory.lastUpdated": "Kali terakhir dikemas kini",
  "directory.contactUnavailable": "Maklumat hubungan tidak tersedia. Rujuk sumber yang disenaraikan.",
  "directory.callAction": "Hubungi agensi",
  "directory.externalLinkNotice": "Pautan luar membuka portal maklumat rasmi; pautan ini bukan integrasi aplikasi.",
  "chat.heading": "Sembang kesiapsiagaan banjir",
  "chat.description": "Tanya tentang kesiapsiagaan banjir menggunakan korpus pengetahuan tempatan yang diluluskan.",
  "chat.inputLabel": "Soalan kesiapsiagaan",
  "chat.send": "Hantar soalan",
  "chat.answerMode": "Mod jawapan",
  "chat.citation": "Petikan",
  "chat.citations": "Petikan",
  "chat.sourceDetails": "Butiran sumber",
  "chat.insufficientEvidence": "Bukti yang diluluskan tidak mencukupi untuk menjawab permintaan itu dengan selamat.",
  "chat.emergencyHeading": "Dapatkan bantuan kecemasan sekarang",
  "chat.callEmergency": "Hubungi 999",
  "chat.avoidFloodwater": "Jangan berjalan, berenang atau memandu melalui air banjir yang bergerak atau tidak diketahui kedalamannya.",
  "chat.followResponders": "Ikut arahan anggota kecemasan.",
  "chat.cannotDispatch": "BanjirReady tidak boleh menghantar perkhidmatan penyelamat.",
  "chat.cannotMonitor": "BanjirReady tidak boleh memantau permintaan menyelamat.",
  "chat.cannotGuaranteeSafety": "BanjirReady tidak boleh menjamin keselamatan semasa.",
  "chat.ambiguousEmergency": "Mesej anda mungkin menerangkan kecemasan. Hubungi perkhidmatan kecemasan dahulu, kemudian jelaskan hanya jika selamat untuk berbuat demikian.",
  "errors.missingContent": "Kandungan ini tidak tersedia dalam Bahasa Melayu.",
  "errors.validation": "Semak maklumat yang ditandakan dan cuba lagi.",
  "errors.invalidRequest": "Permintaan tidak diterima.",
  "errors.serverUnavailable": "Perkhidmatan tempatan tidak tersedia. Panduan kecemasan yang telah dimuatkan masih tersedia.",
  "errors.storageUnavailable": "Penyimpanan tidak tersedia. Anda boleh terus menggunakan sesi ini dalam ingatan.",
  "errors.sourceUnavailable": "Sumber tidak tersedia. Tiada nilai diteka atau digantikan.",
  "errors.providerTimeout": "Penyedia pilihan tidak memberi respons dalam masa yang ditetapkan. Kandungan sandaran tempatan yang selamat sedang digunakan.",
  "errors.providerInvalid": "Penyedia pilihan mengembalikan data tidak sah. Kandungan sandaran tempatan yang selamat sedang digunakan.",
  "errors.unexpected": "Sesuatu telah berlaku. Tiada maklumat peribadi disimpan untuk penyahpepijatan.",
  "errors.retry": "Cuba semula sekali",
  "errors.safeReturn": "Kembali ke panduan keselamatan",
  "privacy.heading": "Privasi dan data tempatan",
  "privacy.noAccount": "Tiada akaun atau identiti diperlukan untuk ciri asas.",
  "privacy.sharedDeviceNotice": "Profil pelayar ini mungkin dikongsi. Keutamaan senarai semak yang disimpan di sini mungkin dapat dilihat oleh pengguna lain profil ini.",
  "privacy.storageAllowlist": "Storan tempatan hanya mengandungi keutamaan bahasa, enam medan senarai semak, versi peraturan senarai semak, keadaan penyelesaian item stabil dan notis yang diperakui.",
  "privacy.retention": "Data yang dibenarkan kekal dalam profil pelayar ini sehingga dikosongkan atau storan pelayar dipadamkan.",
  "privacy.clearProcedure": "Selepas pengesahan, pengosongan data membuang setiap kunci berawalan BanjirReady dan membiarkan data pelayar lain tidak berubah.",
  "privacy.clearAction": "Kosongkan data BanjirReady",
  "privacy.clearConfirm": "Sahkan pengosongan data BanjirReady yang disimpan secara tempatan.",
  "privacy.memoryFallback": "Jika storan pelayar tidak tersedia, ciri terus berfungsi dalam ingatan untuk sesi ini.",
  "privacy.chatNotStored": "Teks mesej sembang tidak disimpan selepas pemprosesan respons atau pembatalan tamat.",
  "privacy.noAnalytics": "Analitik, pengiklanan, rakaman semula sesi, geolokasi dan pengumpulan lokasi latar belakang tidak didayakan.",
  "privacy.enabledIntegrations": "Integrasi luaran yang didayakan",
  "privacy.noneEnabled": "Tiada integrasi luaran didayakan.",
  "limitations.heading": "Batasan",
  "limitations.informationOnly": "BanjirReady hanya menyediakan maklumat kesiapsiagaan.",
  "limitations.noRescueDispatch": "Permintaan menyelamat, penghantaran penyelamat dan pemantauan penyelamatan tidak tersedia.",
  "limitations.noReports": "Laporan pengguna dan penyumberan ramai tidak tersedia.",
  "limitations.noPayments": "Pembayaran, derma dan langganan tidak tersedia.",
  "limitations.noAccounts": "Akaun, log masuk dan penyegerakan merentas peranti tidak tersedia.",
  "limitations.noRoutes": "Pengiraan laluan pemindahan dan jaminan laluan selamat tidak tersedia.",
  "limitations.noForecasts": "Ramalan banjir dan jangkaan paras air tidak tersedia.",
  "limitations.noSafetyGuarantee": "BanjirReady tidak boleh menyatakan bahawa sesuatu tempat selamat pada masa ini atau menjamin keselamatan semasa.",
  "limitations.noProfessionalAdvice": "BanjirReady tidak menyediakan nasihat klinikal, undang-undang, kejuruteraan atau profesional kecemasan.",
  "limitations.noEndorsement": "Kandungan dan status semakan tidak mewakili pengendorsan kerajaan.",
  "limitations.unavailable": "Keupayaan ini di luar skop MVP BanjirReady dan tidak tersedia.",
  "freshness.current": "Semasa mengikut dasar kesegaran yang dikonfigurasikan",
  "freshness.stale": "Lapuk",
  "freshness.unavailable": "Sumber tidak tersedia",
  "freshness.sourceTimestamp": "Cap masa sumber",
  "freshness.retrievalTimestamp": "Cap masa pengambilan",
  "freshness.lastUpdated": "Kali terakhir dikemas kini",
  "freshness.staleWarning": "Maklumat ini lapuk. Semak cap masa sumber sebelum bertindak.",
  "freshness.replacementReason": "Data sumber lapuk telah digantikan dengan data demo deterministik.",
  "demoLabels.demoMode": "Demo Mode / Mod Demo",
  "demoLabels.demoData": "Demo Data / Data Demo",
  "demoLabels.demoGuidance": "Demo Guidance / Panduan Demo",
  "demoLabels.notCurrentOperational": "Not current operational information / Bukan maklumat operasi semasa",
  "demoLabels.liveData": "Data langsung",
  "demoLabels.reviewedGuidance": "Panduan disemak",
  "demoLabels.providerMode": "Mod penyedia",
  "demoLabels.providerAvailability": "Ketersediaan",
  "demoLabels.providerAvailable": "Penyedia tersedia",
  "demoLabels.providerUnavailable": "Penyedia tidak tersedia",
  "demoLabels.providerVerification": "Pengesahan",
  "demoLabels.providerVerified": "Disahkan",
  "demoLabels.providerUnverified": "Tidak disahkan",
  "demoLabels.providerFreshness": "Kesegaran",
  "demoLabels.fallbackProvider": "Penyedia sandaran",
  "demoLabels.fallbackActive": "Sandaran tanpa kelayakan aktif",
  "demoLabels.providerErrorCode": "Kod ralat selamat",
  "demoLabels.providerStatus": "Status penyedia dan sandaran",
  "demoLabels.providerStatusLoading": "Status penyedia sedang disegarkan. Status yang telah dimuatkan masih tersedia.",
  "demoLabels.providerStatusUpdated": "Status penyedia dikemas kini.",
  "demoLabels.providerStatusUnavailable": "Perkhidmatan status penyedia tidak tersedia",
} as const satisfies Readonly<Record<MessageKey, string>>;

const safetyMessages = {
  emergency_escalation: [...SAFETY_MESSAGES_BY_CATEGORY.emergency_escalation],
  water_safety: [...SAFETY_MESSAGES_BY_CATEGORY.water_safety],
  rescue_limitations: [...SAFETY_MESSAGES_BY_CATEGORY.rescue_limitations],
  evidence_limitations: [...SAFETY_MESSAGES_BY_CATEGORY.evidence_limitations],
  scope_limitations: [...SAFETY_MESSAGES_BY_CATEGORY.scope_limitations],
  privacy: [...SAFETY_MESSAGES_BY_CATEGORY.privacy],
  freshness: [...SAFETY_MESSAGES_BY_CATEGORY.freshness],
  demo_status: [...SAFETY_MESSAGES_BY_CATEGORY.demo_status],
  availability_errors: [...SAFETY_MESSAGES_BY_CATEGORY.availability_errors],
  non_endorsement: [...SAFETY_MESSAGES_BY_CATEGORY.non_endorsement],
} as const satisfies Readonly<
  Record<SafetyMessageCategory, readonly MessageKey[]>
>;

export const ENGLISH_CATALOG = {
  version: RESOURCE_CATALOG_VERSION,
  language: "en",
  messages: englishMessages,
  safetyMessages,
} as const satisfies ResourceCatalog;

export const MALAY_CATALOG = {
  version: RESOURCE_CATALOG_VERSION,
  language: "ms",
  messages: malayMessages,
  safetyMessages: {
    emergency_escalation: [...safetyMessages.emergency_escalation],
    water_safety: [...safetyMessages.water_safety],
    rescue_limitations: [...safetyMessages.rescue_limitations],
    evidence_limitations: [...safetyMessages.evidence_limitations],
    scope_limitations: [...safetyMessages.scope_limitations],
    privacy: [...safetyMessages.privacy],
    freshness: [...safetyMessages.freshness],
    demo_status: [...safetyMessages.demo_status],
    availability_errors: [...safetyMessages.availability_errors],
    non_endorsement: [...safetyMessages.non_endorsement],
  },
} as const satisfies ResourceCatalog;

export const RESOURCE_CATALOGS = {
  en: ENGLISH_CATALOG,
  ms: MALAY_CATALOG,
} as const satisfies Readonly<Record<Language, ResourceCatalog>>;

const MISSING_CONTENT_NOTICES = {
  en: englishMessages["errors.missingContent"],
  ms: malayMessages["errors.missingContent"],
} as const satisfies Readonly<Record<Language, string>>;

export type MessageCatalogLookup = Readonly<
  Record<Language, { readonly messages: Readonly<Record<string, unknown>> }>
>;

export function resolveMessage(
  language: Language,
  key: string,
  catalogs: MessageCatalogLookup = RESOURCE_CATALOGS,
): string {
  const selectedMessages = catalogs[language].messages;

  if (!Object.hasOwn(selectedMessages, key)) {
    return MISSING_CONTENT_NOTICES[language];
  }

  const value = selectedMessages[key];
  return typeof value === "string" && value.trim().length > 0
    ? value
    : MISSING_CONTENT_NOTICES[language];
}

