import { StrictMode, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { AppShell } from './AppShell';
import { AgencyCalls } from './AgencyCalls';
import { FamilyNotes } from './FamilyNotes';
import { ModelPredictions } from './ModelPredictions';
import { WeatherDashboard } from './WeatherDashboard';
import { PublishedChecklist, PublishedAssistant } from './PublishedFeatures';
import type { PrimaryFeatureId, PrimaryFeatures } from './AppShell.types';
import { LanguageProvider, useLanguage } from './localization/LanguageProvider';
import './styles.css';
import './product.css';
function Home({ navigate }: { navigate: (id: PrimaryFeatureId) => void }) {
 const { language } = useLanguage(); const ms = language === 'ms';
 return <><div className="premium-hero"><div className="hero-copy"><div className="hero-pill"><span />{ms ? 'BERSAMA, LEBIH BERSEDIA' : 'BETTER PREPARED, TOGETHER'}</div><h3>{ms ? 'Bersedia hari ini.' : 'Prepare today.'}<br /><em>{ms ? 'Lindungi esok.' : 'Protect tomorrow.'}</em></h3><p>{ms ? 'Maklumat cuaca rasmi dan persediaan banjir untuk keluarga anda, di seluruh Malaysia.' : 'Official weather information and flood preparedness for your household, across Malaysia.'}</p><div className="hero-actions"><button onClick={() => navigate('checklist')}>{ms ? 'Mulakan persediaan' : 'Start preparing'} ↗</button><button className="hero-secondary" onClick={() => navigate('directory')}>{ms ? 'Nombor bantuan' : 'Help numbers'} →</button></div><div className="hero-caption">METMalaysia / data.gov.my · NADMA · JPS · JKM</div></div><div className="hero-art" aria-hidden="true"><div className="art-orbit orbit-one" /><div className="art-orbit orbit-two" /><svg viewBox="0 0 400 320"><path d="M90 142 200 48 310 142v142H90Z" fill="#f2f7e7"/><path d="M67 145 200 30 333 145" fill="none" stroke="#b5d9a0" strokeWidth="22" strokeLinecap="round"/><path d="M167 196h67v88h-67z" fill="#284938"/><rect x="112" y="165" width="35" height="38" rx="4" fill="#85bbac"/><rect x="256" y="165" width="35" height="38" rx="4" fill="#85bbac"/><path d="M45 285Q120 255 200 285T355 285" stroke="#80c3b1" strokeWidth="8" fill="none"/><circle cx="300" cy="233" r="44" fill="#d8ed83"/><path d="m279 233 14 14 27-28" fill="none" stroke="#294536" strokeWidth="9" strokeLinecap="round" strokeLinejoin="round"/></svg><div className="art-caption">{ms ? 'Keluarga bersedia, komuniti kuat.' : 'Prepared households. Stronger communities.'}</div></div></div>
 <div className="feature-shortcuts">{[{id: 'checklist' as const, title: ms ? 'Pelan saya' : 'My plan', description: ms ? 'Susun persediaan dan catatan keluarga.' : 'Organise preparation and family notes.'},{id: 'directory' as const, title: ms ? 'Hubungi agensi' : 'Call an agency', description: ms ? 'Talian kecemasan dan maklumat rasmi.' : 'Emergency and official information hotlines.'},{id: 'chat' as const, title: ms ? 'Tanya panduan' : 'Ask for guidance', description: ms ? 'Cari panduan dengan sumber rasmi.' : 'Find guidance with official sources.'}].map(item => <button className="feature-shortcut" key={item.id} onClick={() => navigate(item.id)}><span className="section-eyebrow">BANJIRREADY</span><strong>{item.title}<span aria-hidden="true"> ↗</span></strong><span>{item.description}</span></button>)}</div><WeatherDashboard /><ModelPredictions /><div className="section-top"><div><div className="section-eyebrow">{ms ? 'SUMBER YANG DIPERCAYAI' : 'OFFICIAL INFORMATION'}</div><h3>{ms ? 'Semak terus dengan agensi' : 'Check directly with the agencies'}</h3></div></div><div className="official-grid">{[{name:'JPS',title:ms?'Aras sungai & hujan':'River levels & rainfall',url:'https://publicinfobanjir.water.gov.my/',desc:ms?'Bacaan stesen sebenar di Public InfoBanjir.':'Actual station readings on Public InfoBanjir.'},{name:'JKM',title:ms?'Pusat pemindahan':'Relief centres',url:'https://infobencanajkmv2.jkm.gov.my',desc:ms?'Semak maklumat PPS melalui InfoBencana JKM.':'Check relief-centre information with InfoBencana JKM.'},{name:'NADMA',title:ms?'Maklumat bencana':'Disaster information',url:'https://portalbencana.nadma.gov.my/en/',desc:ms?'Rujukan rasmi pengurusan bencana negara.':'Official national disaster-management information.'}].map(item => <a className="official-card" href={item.url} target="_blank" rel="noreferrer" key={item.name}><span className="agency-monogram">{item.name}</span><span className="outbound">↗</span><h4>{item.title}</h4><p>{item.desc}</p><small>{ms ? 'Buka portal rasmi' : 'Open official portal'} →</small></a>)}</div></>;
}
function Application() {
 const { language } = useLanguage(); const ms = language === 'ms'; const [active, setActive] = useState<PrimaryFeatureId>('guidance');
 const features: PrimaryFeatures = { guidance:{label:ms?'Utama':'Overview',heading:ms?'Ruang persediaan anda':'Your preparedness hub',content:<Home navigate={setActive}/>},checklist:{label:ms?'Pelan saya':'My plan',heading:ms?'Persediaan isi rumah':'Household preparation',content:<><PublishedChecklist/><FamilyNotes/></>},directory:{label:ms?'Hubungi agensi':'Call an agency',heading:ms?'Bantuan, satu panggilan sahaja':'Help is a phone call away',content:<AgencyCalls/>},chat:{label:ms?'Tanya panduan':'Ask for guidance',heading:ms?'Panduan dengan sumber rasmi':'Guidance with official sources',content:<PublishedAssistant/>} };
 return <AppShell features={features} activeFeature={active} onFeatureChange={setActive} showDemoMode={false}/>;
}
const root = document.getElementById('root'); if (!root) throw new Error('Missing root');
createRoot(root).render(<StrictMode><LanguageProvider initialLanguage="ms"><Application/></LanguageProvider></StrictMode>);
