import { useState, type FormEvent } from 'react';
import { useLanguage } from './localization/LanguageProvider';
import { GUIDANCE_SOURCE, publishedGuidance } from './publishedGuidance';
import { isEmergencyQuestion } from '@banjir-ready/fixtures';
const storageKey = 'banjirready-published-plan-v1';
export function PublishedChecklist() {
 const { language } = useLanguage(); const ms = language === 'ms';
 const [done,setDone] = useState<string[]>(() => { try { const saved: unknown = JSON.parse(localStorage.getItem(storageKey) ?? '[]'); return Array.isArray(saved) ? saved.filter((id): id is string => typeof id === 'string' && publishedGuidance.some(g => g.id === id)) : []; } catch { return []; } });
 const [saveEnabled,setSaveEnabled] = useState(false); const [notice,setNotice] = useState('');
 function update(next: string[]) { setDone(next); if (saveEnabled) { try { localStorage.setItem(storageKey,JSON.stringify(next)); } catch { setNotice(ms?'Tidak dapat menyimpan. Kemajuan kekal dalam sesi ini.':'Unable to save. Progress remains in this session.'); } } }
 return <div className="plan-layout"><aside className="plan-intro"><div className="section-eyebrow">{ms?'SEDIKIT DEMI SEDIKIT':'ONE STEP AT A TIME'}</div><h3>{ms?'Pelan kecil. Kesan besar.':'Small steps. A stronger plan.'}</h3><p>{ms?'Mulakan dengan empat tindakan asas daripada panduan keselamatan banjir NADMA.':'Start with four essentials from NADMA’s published flood safety advice.'}</p><div className="plan-score"><strong>{done.length}<span>/4</span></strong><p>{ms?'tindakan ditandakan':'actions checked'}</p></div><progress value={done.length} max={4} aria-label={ms?'Kemajuan persediaan':'Preparation progress'}/><p className="source-caption">{ms?'Ini panduan umum, bukan arahan pemindahan semasa.':'General guidance, not a current evacuation instruction.'}</p></aside><section className="plan-card"><h3>{ms?'Senarai semak anda':'Your checklist'}</h3><ul className="task-list">{publishedGuidance.map(g => <li key={g.id}><label className="task-row"><input type="checkbox" checked={done.includes(g.id)} onChange={e => update(e.target.checked?[...done,g.id]:done.filter(id=>id!==g.id))}/><span>{ms?g.ms:g.en}</span></label><a className="source-link" href={GUIDANCE_SOURCE} target="_blank" rel="noreferrer">NADMA · 20 Dis 2023 · {ms?'halaman 4':'page 4'} ↗</a></li>)}</ul><label className="task-row no-print"><input type="checkbox" checked={saveEnabled} onChange={e => { if(e.target.checked && !window.confirm(ms?'Simpan kemajuan pada pelayar ini? Orang lain yang menggunakan peranti ini boleh melihatnya.':'Save progress in this browser? Others using this device can see it.')) return; setSaveEnabled(e.target.checked); if(e.target.checked) { try {localStorage.setItem(storageKey,JSON.stringify(done));setNotice(ms?'Kemajuan disimpan.':'Progress saved.');} catch {setNotice(ms?'Storan tidak tersedia.':'Storage unavailable.');} } else {try{localStorage.removeItem(storageKey);}catch{/* Storage can be blocked. */}} }}/><span>{ms?'Simpan kemajuan pada peranti ini':'Save progress on this device'}</span></label><div className="action-row no-print"><button onClick={()=>window.print()}>{ms?'Cetak pelan':'Print plan'}</button><button className="secondary" onClick={()=>{if(window.confirm(ms?'Padam kemajuan anda?':'Clear your progress?')){try{localStorage.removeItem(storageKey);}catch{/* Storage can be blocked. */}setDone([]);setSaveEnabled(false);setNotice(ms?'Kemajuan dipadam.':'Progress cleared.');}}}>{ms?'Padam kemajuan':'Clear progress'}</button></div><p role="status">{notice}</p><p className="privacy-note">{ms?'Tiada akaun atau profil peribadi dihantar. Kemajuan yang disimpan kekal sehingga anda memadamnya.':'No account or personal profile is sent. Saved progress remains until you clear it.'}</p></section></div>;
}
export function PublishedAssistant() {
 const { language } = useLanguage(); const ms = language === 'ms'; const [draft,setDraft] = useState(''); const [answer,setAnswer] = useState<'emergency'|'guidance'|'unknown'|null>(null);
 function submit(e:FormEvent){e.preventDefault();if(!draft.trim())return;setAnswer(isEmergencyQuestion(draft)?'emergency':/beg|bag|bekalan|suppl|kanak|child|elektr|electric|persedia|prepar|pindah|evacuat|air|water/i.test(draft)?'guidance':'unknown');setDraft('');}
 return <section className="chat-card"><div className="assistant-mark" aria-hidden="true">✦</div><div className="section-eyebrow">BANJIRREADY ASSISTANT</div><h3>{ms?'Tanya. Faham. Bersedia.':'Ask. Understand. Prepare.'}</h3><p>{ms?'Cari nasihat persediaan daripada panduan NADMA. Pembantu ini menggunakan carian berasaskan peraturan; model AI generatif belum disambungkan.':'Find preparation advice from NADMA guidance. This assistant uses rule-based retrieval; a generative AI model is not connected.'}</p><div className="suggestions">{(ms?['Apa persediaan sebelum banjir?','Keselamatan kanak-kanak','Saya terperangkap']:['How should I prepare?','Children’s safety','I am trapped']).map(q=><button className="secondary" key={q} onClick={()=>setDraft(q)}>{q}</button>)}</div><form onSubmit={submit}><label htmlFor="official-question">{ms?'Soalan anda':'Your question'}</label><textarea id="official-question" value={draft} onChange={e=>setDraft(e.target.value)} rows={3} maxLength={1000} placeholder={ms?'Bagaimana keluarga saya boleh bersedia?':'How can my household prepare?'}/><button disabled={!draft.trim()}>{ms?'Cari panduan':'Find guidance'} ↗</button></form><div aria-live="polite">{answer==='emergency'&&<div className="emergency-chat" role="alert"><h3>{ms?'Hubungi bantuan kecemasan sekarang':'Call emergency services now'}</h3><a className="emergency-action" href="tel:999">{ms?'Hubungi 999':'Call 999'}</a><p>{ms?'Aplikasi tidak menghantar penyelamat. Jangan sentuh peralatan elektrik atau wayar di kawasan banjir.':'The app does not dispatch rescue. Do not touch electrical equipment or wires in flooded areas.'}</p><a href={GUIDANCE_SOURCE} target="_blank" rel="noreferrer">NADMA · {ms?'Sumber panduan':'Guidance source'}</a></div>}{answer==='guidance'&&<div className="chat-answer"><h4>{ms?'Panduan daripada NADMA':'Guidance from NADMA'}</h4>{publishedGuidance.map(g=><article key={g.id}><p>{ms?g.ms:g.en}</p></article>)}<a href={GUIDANCE_SOURCE} target="_blank" rel="noreferrer">NADMA · 20 Dec 2023 · {ms?'halaman 4':'page 4'} ↗</a></div>}{answer==='unknown'&&<p className="information-note">{ms?'Panduan ini tidak dapat mengesahkan keadaan semasa, laluan selamat atau PPS yang beroperasi. Semak sumber rasmi.':'This guidance cannot verify current conditions, safe routes or operating relief centres. Check official sources.'} <a href="https://portalbencana.nadma.gov.my/en/" target="_blank" rel="noreferrer">NADMA ↗</a></p>}</div><p className="privacy-note">{ms?'Soalan diproses pada pelayar dan tidak disimpan.':'Questions are processed in your browser and are not saved.'}</p></section>;
}
