import { useEffect, useState } from 'react';
import { useLanguage } from './localization/LanguageProvider';
export const STATES = ['Johor','Kedah','Kelantan','Melaka','Negeri Sembilan','Pahang','Perak','Perlis','Pulau Pinang','Sabah','Sarawak','Selangor','Terengganu','WP Kuala Lumpur','WP Putrajaya','WP Labuan'];
interface Forecast { location: { location_id: string; location_name: string }; date: string; summary_forecast: string; summary_when: string; morning_forecast: string; afternoon_forecast: string; night_forecast: string; min_temp: number; max_temp: number }
interface Warning { warning_issue: { issued: string; title_bm: string; title_en: string }; valid_from: string | null; valid_to: string | null; heading_bm: string; heading_en: string; text_bm: string; text_en: string; instruction_bm: string; instruction_en: string }
interface Weather { forecasts: { available: boolean; records: Forecast[]; fetchedAt: string | null }; warnings: { available: boolean; records: Warning[]; fetchedAt: string | null }; limited?: boolean }
function malaysiaTime(value: string) { return Date.parse(/Z$|[+-]\d\d:\d\d$/.test(value) ? value : `${value}+08:00`); }
function ForecastIcon({ forecast }: { forecast: string }) {
 const storm = /petir/i.test(forecast); const dry = /tiada/i.test(forecast);
 return <svg viewBox="0 0 64 64" fill="none" aria-hidden="true" className="forecast-icon">
 {dry ? <><circle cx="32" cy="32" r="12" fill="currentColor" opacity=".18" stroke="currentColor" strokeWidth="2.5"/><path d="M32 7v6m0 38v6M7 32h6m38 0h6M14 14l4 4m28 28 4 4M14 50l4-4m28-28 4-4" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/></> : <><path d="M18 40a10 10 0 0 1-1-20 15 15 0 0 1 28-1 11 11 0 0 1 2 21" fill="currentColor" fillOpacity=".1" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/>{storm ? <path d="m33 33-9 14h9l-4 14 15-20H33l5-8Z" fill="#bf8b35" stroke="#bf8b35" strokeLinejoin="round"/> : <path d="m22 46-3 7m15-7-3 7m15-7-3 7" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/>}</>}
 </svg>;
}
export function WeatherDashboard() {
 const { language } = useLanguage(); const ms = language === 'ms';
 const [search, setSearch] = useState(''); const [activeQuery, setActiveQuery] = useState('');
 const [state, setState] = useState('Selangor'); const [data, setData] = useState<Weather | null>(null); const [loading, setLoading] = useState(true); const [failed, setFailed] = useState(false);
 async function load() { setLoading(true); try { const r = await fetch('/api/weather'+(activeQuery ? '?search='+encodeURIComponent(activeQuery) : ''), { signal: AbortSignal.timeout(12000) }); if (!r.ok) throw new Error(); const result = await r.json() as Weather; if (!Array.isArray(result.forecasts?.records) || !Array.isArray(result.warnings?.records)) throw new Error(); setData(result); setFailed(false); if(activeQuery && result.forecasts.records.length) setState(result.forecasts.records[0]!.location.location_id); } catch { setData(null); setFailed(true); } finally { setLoading(false); } }
 useEffect(() => { void load(); const timer = window.setInterval(() => { void load(); }, 120000); return () => window.clearInterval(timer); }, [activeQuery]);
 const today = new Intl.DateTimeFormat('en-CA', { timeZone: 'Asia/Kuala_Lumpur', year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date());
 const locations = activeQuery ? [...new Map((data?.forecasts.records ?? []).map(f => [f.location.location_id, { value: f.location.location_id, label: f.location.location_name+' · '+({St:ms?'Negeri':'State',Ds:ms?'Daerah':'District',Tn:ms?'Bandar':'Town',Rc:ms?'Rekreasi':'Recreation',Dv:ms?'Bahagian':'Division'}[f.location.location_id.slice(0,2)] ?? (ms?'Lokasi':'Location')) }])).values()] : STATES.map(s => ({ value: s, label: s }));
 const forecasts = data?.forecasts.records.filter(f => (activeQuery ? f.location.location_id === state : f.location.location_name === state) && f.date >= today).sort((a,b) => a.date.localeCompare(b.date)) ?? [];
 const activeWarnings = data?.warnings.records.filter(w => w.valid_from !== null && w.valid_to !== null && malaysiaTime(w.valid_from) <= Date.now() && malaysiaTime(w.valid_to) >= Date.now()) ?? [];
 return <section className="weather-section" aria-label={ms ? 'Cuaca seluruh Malaysia' : 'Weather across Malaysia'}>
 <div className="section-top"><div><div className="section-eyebrow">MALAYSIA · METMALAYSIA</div><h3>{ms ? 'Cuaca di negeri anda' : 'Weather in your state'}</h3><p>{ms ? '13 negeri. 3 wilayah persekutuan. Satu tempat untuk bersedia.' : '13 states. 3 federal territories. One place to prepare.'}</p></div><div className="weather-tools"><label htmlFor="state-select">{ms ? 'Pilih lokasi' : 'Select location'}</label><select id="state-select" value={state} onChange={e => setState(e.target.value)}>{activeQuery ? locations.map(s => <option key={s.value} value={s.value}>{s.label}</option>) : <>
<optgroup label={ms ? 'Pantai Timur Semenanjung' : 'East Coast · Peninsular Malaysia'}>{['Kelantan','Terengganu','Pahang'].map(s=><option key={s} value={s}>{s}</option>)}</optgroup>
<optgroup label={ms ? 'Semenanjung · negeri dan wilayah lain' : 'Peninsular Malaysia · other states and territories'}>{['Perlis','Kedah','Pulau Pinang','Perak','Selangor','Negeri Sembilan','Melaka','Johor','WP Kuala Lumpur','WP Putrajaya'].map(s=><option key={s} value={s}>{s}</option>)}</optgroup>
<optgroup label={ms ? 'Malaysia Timur' : 'East Malaysia'}>{['Sabah','Sarawak','WP Labuan'].map(s=><option key={s} value={s}>{s}</option>)}</optgroup>
</>}</select><button type="button" onClick={() => { void load(); }} disabled={loading}>{ms ? 'Muat semula' : 'Refresh'}</button></div></div>
 <form className="forecast-search official-search" onSubmit={e=>{e.preventDefault();setData(null);setActiveQuery(search.trim());}}><label htmlFor="official-location-search">{ms?'Cari ramalan rasmi bandar / daerah':'Search official town / district forecasts'}</label><div><input id="official-location-search" value={search} onChange={e=>setSearch(e.target.value)} minLength={2} maxLength={80} required placeholder="Kuantan, Langkawi, Kuching…"/><button disabled={loading}>{ms?'Cari':'Search'}</button><button type="button" onClick={()=>{setSearch('');setActiveQuery('');setState('Selangor');}}>{ms?'Semua negeri':'All states'}</button></div></form>
 {activeQuery && <p className="source-caption">{ms?'Padanan lokasi rasmi untuk':'Official location matches for'} “{activeQuery}”. {ms?'Pilih padanan di atas. Nama lokasi mengikut API METMalaysia.':'Choose a match above. Location names follow the METMalaysia API.'}</p>}
 {data?.limited && <p role="status">{ms?'Hasil carian terhad. Gunakan nama tempat yang lebih khusus.':'Search results are limited. Use a more specific place name.'}</p>}
 <p className="feed-status" role="status">{loading ? (ms ? 'Mendapatkan data rasmi…' : 'Fetching official data…') : data?.forecasts.available ? `${ms ? 'Diperoleh' : 'Retrieved'} ${new Date(data.forecasts.fetchedAt ?? '').toLocaleString(ms ? 'ms-MY' : 'en-MY', { timeZone: 'Asia/Kuala_Lumpur' })} MYT · data.gov.my · CC BY 4.0` : (ms ? 'Data rasmi tidak tersedia. Cuba lagi atau semak portal rasmi.' : 'Official data unavailable. Retry or check the official portals.')}</p>
 <div className="forecast-grid">{forecasts.slice(0,7).map((f,i) => <article className={`forecast-card ${i === 0 ? 'forecast-today' : ''}`} key={f.date}><div className="forecast-day">{f.date === today ? (ms ? 'Hari ini' : 'Today') : new Date(`${f.date}T12:00:00+08:00`).toLocaleDateString(ms ? 'ms-MY' : 'en-MY', { weekday: 'short' })}<span>{new Date(`${f.date}T12:00:00+08:00`).toLocaleDateString(ms ? 'ms-MY' : 'en-MY', { day: 'numeric', month: 'short', timeZone: 'Asia/Kuala_Lumpur' })}</span></div><div className="forecast-visual"><ForecastIcon forecast={f.summary_forecast}/><div className="forecast-temperature"><strong>{f.max_temp}<span>°C</span></strong><span className="forecast-low">{ms ? 'Minimum' : 'Low'} {f.min_temp}°</span></div></div><p>{f.summary_forecast}</p><small className="forecast-period">{f.summary_when}</small><div className="forecast-timeline"><div><span>{ms ? 'Pagi' : 'Morning'}</span><p>{f.morning_forecast}</p></div><div><span>{ms ? 'Petang' : 'Afternoon'}</span><p>{f.afternoon_forecast}</p></div><div><span>{ms ? 'Malam' : 'Night'}</span><p>{f.night_forecast}</p></div></div><details><summary>{ms ? 'Butiran' : 'Details'}</summary><p>{ms ? 'Pagi' : 'Morning'}: {f.morning_forecast}</p><p>{ms ? 'Petang' : 'Afternoon'}: {f.afternoon_forecast}</p><p>{ms ? 'Malam' : 'Night'}: {f.night_forecast}</p></details></article>)}</div>
 {!loading && !forecasts.length && <p className="information-note">{ms ? 'Tiada ramalan semasa diterima untuk negeri ini. Ini tidak bermaksud tiada risiko banjir.' : 'No current forecast received for this state. This does not mean there is no flood risk.'}</p>}
 <p className="source-caption">{ms ? 'Ramalan negeri, bukan bacaan hujan atau ramalan banjir setempat. Teks ramalan rasmi dalam Bahasa Melayu.' : 'State forecasts, not rainfall measurements or local flood predictions. Official forecast text is in Bahasa Melayu.'} <a href="https://developer.data.gov.my/realtime-api/weather" target="_blank" rel="noreferrer">{ms ? 'Sumber & kaedah' : 'Source & methodology'} ↗</a></p>
 <div className="warning-panel"><div className="section-eyebrow">{ms ? 'BULETIN RASMI · SELURUH MALAYSIA' : 'OFFICIAL BULLETINS · ALL MALAYSIA'}</div><h3>{ms ? 'Amaran cuaca METMalaysia' : 'METMalaysia weather warnings'}</h3><p>{ms ? 'Amaran nasional ditunjukkan penuh. Baca kawasan dan tempoh terlibat; pemilih negeri tidak menapis amaran.' : 'National warnings are shown in full. Read the affected areas and validity; the state selector does not filter warnings.'}</p>
 {activeWarnings.map((w,i) => <details className="warning-entry" key={`${w.warning_issue.issued}-${i}`}><summary>{ms ? w.heading_bm || w.warning_issue.title_bm : w.heading_en || w.warning_issue.title_en}</summary><p>{ms ? w.text_bm : w.text_en}</p><p>{ms ? w.instruction_bm : w.instruction_en}</p><small>{ms ? 'Bermula' : 'Valid from'}: {w.valid_from} MYT · {ms ? 'Dikeluarkan' : 'Issued'}: {w.warning_issue.issued} MYT · {ms ? 'Sah hingga' : 'Valid until'}: {w.valid_to} MYT</small></details>)}
 {!loading && !activeWarnings.length && <p>{data?.warnings.available && !failed ? (ms ? 'Tiada buletin aktif diterima daripada API. Ini bukan pengesahan bahawa kawasan anda selamat.' : 'No active bulletin received from the API. This does not confirm your area is safe.') : (ms ? 'Suapan amaran tidak tersedia. Semak METMalaysia.' : 'Warning feed unavailable. Check METMalaysia.')}</p>}<a href="https://www.met.gov.my/" target="_blank" rel="noreferrer">METMalaysia ↗</a></div>
 </section>;
}






